### ISSUE TITLE
CS1238

### ISSUE THREAD

**Issue by djbr1** [yasir-shahzad/CS1237-24-Bit-ADC-Module#1]
Hello
Thanks for schematics and PCB for CS1237.
Do you have schematics and PCB layout for CS1238 (dual-channel) ?
Thank you

**Comment by yasir-shahzad** [comment]
Hi, yes, I have that one. I’ll share them with you in 2–3 days.

**Comment by djbr1** [comment]
Hi Yasir
Thanks for feedback, awaiting schematic and PCB for CS1238 (Dual-channel)

**Comment by yasir-shahzad** [comment]
Hi! I have uploaded the design files for the CS1238 module here:  
[GitHub Repository](https://github.com/yasir-shahzad/CS1238-24-Bit-ADC-Module)  

You can also purchase the module from AliExpress:  
[AliExpress Link](https://www.aliexpress.com/item/1005005560934399.html)




![Screenshot_1](https://github.com/user-attachments/assets/f9b1fc4b-a7c1-4eeb-98e1-5bf4c6b8a046)

**Comment by djbr1** [comment]
Thank you for schematic and PCB pictures, my CS1238 breakout just arrived from Aliexpress.
My project is described here:  https://blog.hb9txb.ch
regards
Branko
